Siganushka\OrderBundle\Entity\OrderAdjustment:
    attributes:
        id:
            groups: ['order:item', 'order:collection']
        amount:
            groups: ['order:item', 'order:collection']
        type:
            groups: ['order:item', 'order:collection']
        label:
            groups: ['order:item', 'order:collection']
        createdAt:
            groups: ['order:item', 'order:collection']
        updatedAt:
            groups: ['order:item', 'order:collection']
