Siganushka\OrderBundle\Entity\Order:
    attributes:
        number:
            groups: ['order:item', 'order:collection']
        itemsTotal:
            groups: ['order:item', 'order:collection']
        adjustmentsTotal:
            groups: ['order:item', 'order:collection']
        total:
            groups: ['order:item', 'order:collection']
        state:
            groups: ['order:item', 'order:collection']
        note:
            groups: ['order:item', 'order:collection']
        free:
            groups: ['order:item', 'order:collection']
        items:
            groups: ['order:item', 'order:collection']
        adjustments:
            groups: ['order:item', 'order:collection']
        createdAt:
            groups: ['order:item', 'order:collection']
        updatedAt:
            groups: ['order:item', 'order:collection']
