Siganushka\OrderBundle\Entity\Order:
    attributes:
        id:
            ignore: true
        stateAsString:
            ignore: true
        items:
            groups: ['item', 'collection']
        adjustments:
            groups: ['item', 'collection']

Siganushka\OrderBundle\Model\OrderItemSubjectInterface:
    attributes:
        subjectTitle:
            ignore: true
        subjectPrice:
            ignore: true
        subjectExtra:
            ignore: true
        subjectImg:
            ignore: true

Siganushka\OrderBundle\Model\StockableInterface:
    attributes:
        availableStock:
            ignore: true
